name: morphometrics
dependencies:
  - python=3.9.0
  - conda-forge::matplotlib=3.3.3
  - conda-forge::pandas
  - conda-forge::graph-tool
  - pathlib
  - pip>=20.0.2
  - pip:
    - git+https://github.com/bbarad/Pyto.git
    - git+https://github.com/kalemaria/pycurv.git
    - pymeshlab
    - pyyaml
